### ISSUE TITLE
Click and Drag Bug

### ISSUE THREAD

**Issue by Kryptiku** [Kryptiku/Pathfinding_Civilization#5]
First click and drag is consistent but subsequent click and drags produces inconsistent wall node placements

**Comment by KazeVortex** [comment]
Remove the placing animation

**Comment by Kryptiku** [comment]
> Remove the placing animation

LGTM! 👍

**Comment by Kryptiku** [comment]
Still up for implementation and testing

**Comment by KazeVortex** [comment]
Removed animation lines for applying walls on CSS. Clement had the same issue. Closed.
